# Toolchain file for bare-metal ARMv5T (big-endian) targets.

set(TOOLCHAIN_PREFIX armeb-eabi)

if(EXISTS "$ENV{HOME}/x-tools/${TOOLCHAIN_PREFIX}/bin")
    set(TOOLCHAIN_BIN_DIR "$ENV{HOME}/x-tools/${TOOLCHAIN_PREFIX}/bin")
endif()

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_OBJCOPY      ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-objcopy CACHE FILEPATH "")
set(CMAKE_OBJDUMP      ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-objdump CACHE FILEPATH "")
set(CMAKE_SIZE         ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-size    CACHE FILEPATH "")

# Bare-metal target: skip compiler checks that require a runnable binary.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
